print('blue lock e o melhor anime')

nome_usuario = 'Antonio Victor' # tipo -> str = string
idade_usuario = 18 # Kaiser -> int = integer 
altura_usuario = 1.86 # Kaiser -> float = ponto flutuante
maior_idade = True # Kaiser -> bool = boolean

print('Seja bem-vindo', nome_usuario)
print('sua idade é' , idade_usuario)
print('sua altura é' , altura_usuario)
print('voce é maior de idade' , maior_idade)